export const produits = {
  homme: [
    {
      id: 1,
      nom: "Saccoche Goyard",
      prix: "220€",
      image: "/images/Belvedere_MM_gris.jpeg",
    },
    {
      id: 2,
      nom: "Chemise Luxe Homme",
      prix: "199€",
      image: "/images/chemise-homme.jpg",
    },
    {
      id: 3,
      nom: "Blouson Luxe Homme",
      prix: "799€",
      image: "/images/blouson-homme.jpg",
    },
    {
      id: 4,
      nom: "Chaussures Luxe Homme",
      prix: "399€",
      image: "/images/chaussures-homme.jpg",
    },
    { id: 5, nom: "Sac Homme", prix: "349€", image: "/images/sac-homme.jpg" },
    {
      id: 6,
      nom: "Ceinture Luxe Homme",
      prix: "129€",
      image: "/images/ceinture-homme.jpg",
    },
    {
      id: 7,
      nom: "Portefeuille Homme",
      prix: "149€",
      image: "/images/portefeuille-homme.jpg",
    },
    {
      id: 8,
      nom: "Cravate Luxe Homme",
      prix: "89€",
      image: "/images/cravate-homme.jpg",
    },
    {
      id: 9,
      nom: "Lunettes Homme",
      prix: "299€",
      image: "/images/lunettes-homme.jpg",
    },
    {
      id: 10,
      nom: "Parka Luxe Homme",
      prix: "999€",
      image: "/images/parka-homme.jpg",
    },
  ],
  femme: [
    {
      id: 1,
      nom: "Sac à main Luxe Femme",
      prix: "699€",
      image: "/images/sac-femme.jpg",
    },
    {
      id: 2,
      nom: "Robe Luxe Femme",
      prix: "399€",
      image: "/images/robe-femme.jpg",
    },
    {
      id: 3,
      nom: "Chaussures Luxe Femme",
      prix: "349€",
      image: "/images/chaussures-femme.jpg",
    },
    {
      id: 4,
      nom: "Blouse Femme",
      prix: "199€",
      image: "/images/blouse-femme.jpg",
    },
    {
      id: 5,
      nom: "Pochette Luxe Femme",
      prix: "249€",
      image: "/images/pochette-femme.jpg",
    },
    {
      id: 6,
      nom: "Boucles d’oreilles",
      prix: "129€",
      image: "/images/boucles-femme.jpg",
    },
    {
      id: 7,
      nom: "Bracelet Luxe Femme",
      prix: "179€",
      image: "/images/bracelet-femme.jpg",
    },
    {
      id: 8,
      nom: "Manteau Femme",
      prix: "899€",
      image: "/images/manteau-femme.jpg",
    },
    {
      id: 9,
      nom: "Lunettes Femme",
      prix: "299€",
      image: "/images/lunettes-femme.jpg",
    },
    {
      id: 10,
      nom: "Chapeau Luxe Femme",
      prix: "159€",
      image: "/images/chapeau-femme.jpg",
    },
  ],
  maroquinerie: [
    {
      id: 1,
      nom: "Portefeuille Luxe",
      prix: "149€",
      image: "/images/portefeuille.jpg",
    },
    { id: 2, nom: "Sacoche Luxe", prix: "399€", image: "/images/sacoche.jpg" },
    {
      id: 3,
      nom: "Porte-cartes",
      prix: "99€",
      image: "/images/porte-cartes.jpg",
    },
    {
      id: 4,
      nom: "Sac de voyage",
      prix: "699€",
      image: "/images/sac-voyage.jpg",
    },
    { id: 5, nom: "Trousse Luxe", prix: "129€", image: "/images/trousse.jpg" },
    {
      id: 6,
      nom: "Ceinture Luxe",
      prix: "129€",
      image: "/images/ceinture.jpg",
    },
    {
      id: 7,
      nom: "Pochette Luxe",
      prix: "249€",
      image: "/images/pochette.jpg",
    },
    {
      id: 8,
      nom: "Cartable Luxe",
      prix: "399€",
      image: "/images/cartable.jpg",
    },
    {
      id: 9,
      nom: "Sac bandoulière",
      prix: "349€",
      image: "/images/sac-bandouliere.jpg",
    },
    {
      id: 10,
      nom: "Sac à dos Luxe",
      prix: "499€",
      image: "/images/sac-a-dos.jpg",
    },
  ],
  sneakers: [
    {
      id: 1,
      nom: "Sneakers Luxe Homme",
      prix: "299€",
      image: "/images/sneakers-homme.jpg",
    },
    {
      id: 2,
      nom: "Sneakers Luxe Femme",
      prix: "299€",
      image: "/images/sneakers-femme.jpg",
    },
    {
      id: 3,
      nom: "Sneakers Edition Limitée",
      prix: "399€",
      image: "/images/sneakers-limitee.jpg",
    },
    {
      id: 4,
      nom: "Sneakers Casual",
      prix: "249€",
      image: "/images/sneakers-casual.jpg",
    },
    {
      id: 5,
      nom: "Sneakers Sport Luxe",
      prix: "349€",
      image: "/images/sneakers-sport.jpg",
    },
    {
      id: 6,
      nom: "Sneakers Vintage",
      prix: "279€",
      image: "/images/sneakers-vintage.jpg",
    },
    {
      id: 7,
      nom: "Sneakers Haute Couture",
      prix: "499€",
      image: "/images/sneakers-haute.jpg",
    },
    {
      id: 8,
      nom: "Sneakers Trendy",
      prix: "319€",
      image: "/images/sneakers-trendy.jpg",
    },
    {
      id: 9,
      nom: "Sneakers Luxe Mix",
      prix: "389€",
      image: "/images/sneakers-mix.jpg",
    },
    {
      id: 10,
      nom: "Sneakers Edition Artistique",
      prix: "429€",
      image: "/images/sneakers-art.jpg",
    },
  ],
};
